apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/smirnov-mi/my-charts.git
    targetRevision: HEAD
    path: dev
    # helm specific config
    #chart: chart-name  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    #helm:
    #  passCredentials: false # If true then adds --pass-credentials to Helm commands to pass credentials to all domains

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
